package net.minecraft.world.level.biome;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceKey;

public abstract class Biomes {
    public static final ResourceKey<Biome> OCEAN;
    public static final ResourceKey<Biome> PLAINS;
    public static final ResourceKey<Biome> DESERT;
    public static final ResourceKey<Biome> MOUNTAINS;
    public static final ResourceKey<Biome> FOREST;
    public static final ResourceKey<Biome> TAIGA;
    public static final ResourceKey<Biome> SWAMP;
    public static final ResourceKey<Biome> RIVER;
    public static final ResourceKey<Biome> NETHER_WASTES;
    public static final ResourceKey<Biome> THE_END;
    public static final ResourceKey<Biome> FROZEN_OCEAN;
    public static final ResourceKey<Biome> FROZEN_RIVER;
    public static final ResourceKey<Biome> SNOWY_TUNDRA;
    public static final ResourceKey<Biome> SNOWY_MOUNTAINS;
    public static final ResourceKey<Biome> MUSHROOM_FIELDS;
    public static final ResourceKey<Biome> MUSHROOM_FIELD_SHORE;
    public static final ResourceKey<Biome> BEACH;
    public static final ResourceKey<Biome> DESERT_HILLS;
    public static final ResourceKey<Biome> WOODED_HILLS;
    public static final ResourceKey<Biome> TAIGA_HILLS;
    public static final ResourceKey<Biome> MOUNTAIN_EDGE;
    public static final ResourceKey<Biome> JUNGLE;
    public static final ResourceKey<Biome> JUNGLE_HILLS;
    public static final ResourceKey<Biome> JUNGLE_EDGE;
    public static final ResourceKey<Biome> DEEP_OCEAN;
    public static final ResourceKey<Biome> STONE_SHORE;
    public static final ResourceKey<Biome> SNOWY_BEACH;
    public static final ResourceKey<Biome> BIRCH_FOREST;
    public static final ResourceKey<Biome> BIRCH_FOREST_HILLS;
    public static final ResourceKey<Biome> DARK_FOREST;
    public static final ResourceKey<Biome> SNOWY_TAIGA;
    public static final ResourceKey<Biome> SNOWY_TAIGA_HILLS;
    public static final ResourceKey<Biome> GIANT_TREE_TAIGA;
    public static final ResourceKey<Biome> GIANT_TREE_TAIGA_HILLS;
    public static final ResourceKey<Biome> WOODED_MOUNTAINS;
    public static final ResourceKey<Biome> SAVANNA;
    public static final ResourceKey<Biome> SAVANNA_PLATEAU;
    public static final ResourceKey<Biome> BADLANDS;
    public static final ResourceKey<Biome> WOODED_BADLANDS_PLATEAU;
    public static final ResourceKey<Biome> BADLANDS_PLATEAU;
    public static final ResourceKey<Biome> SMALL_END_ISLANDS;
    public static final ResourceKey<Biome> END_MIDLANDS;
    public static final ResourceKey<Biome> END_HIGHLANDS;
    public static final ResourceKey<Biome> END_BARRENS;
    public static final ResourceKey<Biome> WARM_OCEAN;
    public static final ResourceKey<Biome> LUKEWARM_OCEAN;
    public static final ResourceKey<Biome> COLD_OCEAN;
    public static final ResourceKey<Biome> DEEP_WARM_OCEAN;
    public static final ResourceKey<Biome> DEEP_LUKEWARM_OCEAN;
    public static final ResourceKey<Biome> DEEP_COLD_OCEAN;
    public static final ResourceKey<Biome> DEEP_FROZEN_OCEAN;
    public static final ResourceKey<Biome> THE_VOID;
    public static final ResourceKey<Biome> SUNFLOWER_PLAINS;
    public static final ResourceKey<Biome> DESERT_LAKES;
    public static final ResourceKey<Biome> GRAVELLY_MOUNTAINS;
    public static final ResourceKey<Biome> FLOWER_FOREST;
    public static final ResourceKey<Biome> TAIGA_MOUNTAINS;
    public static final ResourceKey<Biome> SWAMP_HILLS;
    public static final ResourceKey<Biome> ICE_SPIKES;
    public static final ResourceKey<Biome> MODIFIED_JUNGLE;
    public static final ResourceKey<Biome> MODIFIED_JUNGLE_EDGE;
    public static final ResourceKey<Biome> TALL_BIRCH_FOREST;
    public static final ResourceKey<Biome> TALL_BIRCH_HILLS;
    public static final ResourceKey<Biome> DARK_FOREST_HILLS;
    public static final ResourceKey<Biome> SNOWY_TAIGA_MOUNTAINS;
    public static final ResourceKey<Biome> GIANT_SPRUCE_TAIGA;
    public static final ResourceKey<Biome> GIANT_SPRUCE_TAIGA_HILLS;
    public static final ResourceKey<Biome> MODIFIED_GRAVELLY_MOUNTAINS;
    public static final ResourceKey<Biome> SHATTERED_SAVANNA;
    public static final ResourceKey<Biome> SHATTERED_SAVANNA_PLATEAU;
    public static final ResourceKey<Biome> ERODED_BADLANDS;
    public static final ResourceKey<Biome> MODIFIED_WOODED_BADLANDS_PLATEAU;
    public static final ResourceKey<Biome> MODIFIED_BADLANDS_PLATEAU;
    public static final ResourceKey<Biome> BAMBOO_JUNGLE;
    public static final ResourceKey<Biome> BAMBOO_JUNGLE_HILLS;
    public static final ResourceKey<Biome> SOUL_SAND_VALLEY;
    public static final ResourceKey<Biome> CRIMSON_FOREST;
    public static final ResourceKey<Biome> WARPED_FOREST;
    public static final ResourceKey<Biome> BASALT_DELTAS;
    
    private static ResourceKey<Biome> register(final String string) {
        return ResourceKey.<Biome>create(Registry.BIOME_REGISTRY, new ResourceLocation(string));
    }
    
    static {
        OCEAN = register("ocean");
        PLAINS = register("plains");
        DESERT = register("desert");
        MOUNTAINS = register("mountains");
        FOREST = register("forest");
        TAIGA = register("taiga");
        SWAMP = register("swamp");
        RIVER = register("river");
        NETHER_WASTES = register("nether_wastes");
        THE_END = register("the_end");
        FROZEN_OCEAN = register("frozen_ocean");
        FROZEN_RIVER = register("frozen_river");
        SNOWY_TUNDRA = register("snowy_tundra");
        SNOWY_MOUNTAINS = register("snowy_mountains");
        MUSHROOM_FIELDS = register("mushroom_fields");
        MUSHROOM_FIELD_SHORE = register("mushroom_field_shore");
        BEACH = register("beach");
        DESERT_HILLS = register("desert_hills");
        WOODED_HILLS = register("wooded_hills");
        TAIGA_HILLS = register("taiga_hills");
        MOUNTAIN_EDGE = register("mountain_edge");
        JUNGLE = register("jungle");
        JUNGLE_HILLS = register("jungle_hills");
        JUNGLE_EDGE = register("jungle_edge");
        DEEP_OCEAN = register("deep_ocean");
        STONE_SHORE = register("stone_shore");
        SNOWY_BEACH = register("snowy_beach");
        BIRCH_FOREST = register("birch_forest");
        BIRCH_FOREST_HILLS = register("birch_forest_hills");
        DARK_FOREST = register("dark_forest");
        SNOWY_TAIGA = register("snowy_taiga");
        SNOWY_TAIGA_HILLS = register("snowy_taiga_hills");
        GIANT_TREE_TAIGA = register("giant_tree_taiga");
        GIANT_TREE_TAIGA_HILLS = register("giant_tree_taiga_hills");
        WOODED_MOUNTAINS = register("wooded_mountains");
        SAVANNA = register("savanna");
        SAVANNA_PLATEAU = register("savanna_plateau");
        BADLANDS = register("badlands");
        WOODED_BADLANDS_PLATEAU = register("wooded_badlands_plateau");
        BADLANDS_PLATEAU = register("badlands_plateau");
        SMALL_END_ISLANDS = register("small_end_islands");
        END_MIDLANDS = register("end_midlands");
        END_HIGHLANDS = register("end_highlands");
        END_BARRENS = register("end_barrens");
        WARM_OCEAN = register("warm_ocean");
        LUKEWARM_OCEAN = register("lukewarm_ocean");
        COLD_OCEAN = register("cold_ocean");
        DEEP_WARM_OCEAN = register("deep_warm_ocean");
        DEEP_LUKEWARM_OCEAN = register("deep_lukewarm_ocean");
        DEEP_COLD_OCEAN = register("deep_cold_ocean");
        DEEP_FROZEN_OCEAN = register("deep_frozen_ocean");
        THE_VOID = register("the_void");
        SUNFLOWER_PLAINS = register("sunflower_plains");
        DESERT_LAKES = register("desert_lakes");
        GRAVELLY_MOUNTAINS = register("gravelly_mountains");
        FLOWER_FOREST = register("flower_forest");
        TAIGA_MOUNTAINS = register("taiga_mountains");
        SWAMP_HILLS = register("swamp_hills");
        ICE_SPIKES = register("ice_spikes");
        MODIFIED_JUNGLE = register("modified_jungle");
        MODIFIED_JUNGLE_EDGE = register("modified_jungle_edge");
        TALL_BIRCH_FOREST = register("tall_birch_forest");
        TALL_BIRCH_HILLS = register("tall_birch_hills");
        DARK_FOREST_HILLS = register("dark_forest_hills");
        SNOWY_TAIGA_MOUNTAINS = register("snowy_taiga_mountains");
        GIANT_SPRUCE_TAIGA = register("giant_spruce_taiga");
        GIANT_SPRUCE_TAIGA_HILLS = register("giant_spruce_taiga_hills");
        MODIFIED_GRAVELLY_MOUNTAINS = register("modified_gravelly_mountains");
        SHATTERED_SAVANNA = register("shattered_savanna");
        SHATTERED_SAVANNA_PLATEAU = register("shattered_savanna_plateau");
        ERODED_BADLANDS = register("eroded_badlands");
        MODIFIED_WOODED_BADLANDS_PLATEAU = register("modified_wooded_badlands_plateau");
        MODIFIED_BADLANDS_PLATEAU = register("modified_badlands_plateau");
        BAMBOO_JUNGLE = register("bamboo_jungle");
        BAMBOO_JUNGLE_HILLS = register("bamboo_jungle_hills");
        SOUL_SAND_VALLEY = register("soul_sand_valley");
        CRIMSON_FOREST = register("crimson_forest");
        WARPED_FOREST = register("warped_forest");
        BASALT_DELTAS = register("basalt_deltas");
    }
}
